// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CompanyInput struct {
	Name      string           `json:"name"`
	Location  *LocationInput   `json:"location"`
	Employees []*EmployeeInput `json:"employees"`
}

type EmployeeInput struct {
	Location *LocationInput `json:"location"`
	Name     string         `json:"name"`
	Age      int            `json:"age"`
	Gender   string         `json:"gender"`
}

type LocationInput struct {
	Longitude int    `json:"longitude"`
	Latitude  int    `json:"latitude"`
	City      string `json:"city"`
}

type NewTodo struct {
	Text   string  `json:"text"`
	UserID *string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
